// Generated by CoffeeScript 1.9.2
(function() {
  require.config({
    baseUrl: 'js/libs',
    paths: {
      jquery: 'jquery-2.1.3'
    }
  });

  requirejs(['jquery', 'underscore', 'recorder', 'sequencer'], function($, _, Recorder, Sequencer) {
    return Recorder.getUserPermission(function() {
      Recorder.startRecording();
      console.log('Recording...');
      return setTimeout((function() {
        var buffer;
        buffer = Recorder.stopRecording();
        console.log('Stopped Recording...');
        Sequencer.addSample('record1', buffer, [1, 0, 1, 0, 0, 0, 1, 0]);
        return Sequencer.start();
      }), 500);
    });
  });

}).call(this);
